import { EXAMPLE_CSV, MAX_BYTES, currentState, computeSums } from './lettrage.mjs';
/** DOM only via textContent ; mémoire volatile, Worker remplaçable et annulable. */
export function initLettrage() {
  const root=document.querySelector('[data-lettrage]');if(!root)return;
  const q=s=>root.querySelector(s),status=q('[data-status]'),error=q('[data-error]'),file=q('#lettrage-file');
  let active=null,pending=null,result=null,decisions={},pairPage=0,linePage=0,seq=0,exportBusy=false;
  const fail=message=>{error.textContent=message;error.hidden=false;file.setAttribute('aria-invalid','true');error.focus();};
  const clearError=()=>{error.hidden=true;error.textContent='';file.removeAttribute('aria-invalid');};
  const exportButtons=()=>{for(const b of [q('[data-copy]'),q('[data-export]')])b.disabled=exportBusy||!!pending||!result;};
  function table(target,caption,headers,rows){target.replaceChildren();const cap=document.createElement('caption');cap.textContent=caption;target.append(cap);const thead=document.createElement('thead'),tr=document.createElement('tr');for(const h of headers){const th=document.createElement('th');th.scope='col';th.textContent=h;tr.append(th);}thead.append(tr);target.append(thead);const body=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const value of row){const td=document.createElement('td');if(value instanceof Node)td.append(value);else td.textContent=String(value??'');tr.append(td);}body.append(tr);}target.append(body);}
  function actions(pair){const box=document.createElement('div');box.className='decision-actions';for(const [state,label] of [['accepté','Accepter'],['refusé','Refuser'],['proposé','Revenir à proposé']]){const b=document.createElement('button');b.type='button';b.className='btn btn-contour';b.textContent=label;b.setAttribute('aria-label',`${label} la paire ${pair.key}`);b.disabled=(decisions[pair.key]??'proposé')===state;b.addEventListener('click',()=>{if(state==='proposé')delete decisions[pair.key];else decisions[pair.key]=state;render();status.textContent=`Paire ${pair.key} : ${state}. Rapport et sommes actualisés.`;const replacement=q('[data-pairs]').querySelector(`[data-pair="${pair.key}"] button:not(:disabled)`);replacement?.focus({preventScroll:true});});box.dataset.pair=pair.key;box.append(b);}return box;}
  function pager(prefix,page,count,size){const pages=Math.max(1,Math.ceil(count/size));q(`[data-${prefix}-page]`).textContent=`Page ${page+1} / ${pages} — ${count} ${prefix==='pair'?'paire(s)':'ligne(s)'} au total`;q(`[data-${prefix}-prev]`).disabled=page===0;q(`[data-${prefix}-next]`).disabled=page+1>=pages;}
  function render(){if(!result)return;const counts={};for(const l of result.lines){const s=currentState(l,decisions);counts[s]=(counts[s]??0)+1;}q('[data-summary]').textContent=`${result.lines.length} lignes source ; ${result.pairs.length} paire(s), ${result.ambiguous.length} groupe(s) ambigu(s). États des lignes : ${Object.entries(counts).map(([k,v])=>`${v} ${k}`).join(' ; ')}.`;
    table(q('[data-pairs]'),'Paires exactes — décisions courantes',['Paire / état','Identifiants / lignes source','Compte / tiers / devise','Montant / référence','Règle','Décision'],result.pairs.slice(pairPage*25,(pairPage+1)*25).map(p=>[`${p.key} : ${decisions[p.key]??'proposé'}`,p.ids.map((id,i)=>`${id} (ligne ${p.sourceLines[i]})`).join('\n'),`${p.compte} / ${p.tiers} / ${p.devise}`,`${p.amount} / ${p.reference||'sans référence'}`,p.rule,actions(p)]));pager('pair',pairPage,result.pairs.length,25);
    const filter=q('#lettrage-filter').value;const lines=result.lines.filter(l=>filter==='all'||currentState(l,decisions)===filter);linePage=Math.min(linePage,Math.max(0,Math.ceil(lines.length/50)-1));
    table(q('[data-lines]'),'Lignes et motifs — aucune ligne supprimée',['État / groupe','Ligne source','Identifiant','Compte','Tiers','Référence','Date','Débit','Crédit','Devise','Motif'],lines.slice(linePage*50,(linePage+1)*50).map(l=>[`${currentState(l,decisions)} ${l.pairKey??l.groupKey??''}`,l.sourceLine,l.id,l.compte,l.tiers,l.reference,l.date,l.debit,l.credit,l.devise,l.reasons.join(' ; ')]));pager('line',linePage,lines.length,50);
    table(q('[data-sums]'),'Sommes exactes sans conversion',['Devise','État','Lignes','Illisibles','Débit','Crédit','Solde'],computeSums(result,decisions).map(s=>[s.devise,s.state,s.count,s.unreadable,s.debit,s.credit,s.balance]));q('[data-result]').hidden=false;q('[data-fallback]').hidden=true;q('[data-fallback-label]').hidden=true;q('[data-fallback]').value='';exportButtons();
  }
  const stopPending=()=>{pending?.terminate();pending=null;q('[data-cancel]').hidden=true;exportButtons();};
  const makeWorker=()=>new Worker(new URL('../workers/lettrage.worker.mjs',import.meta.url),{name:'memlia-lettrage-local'});
  const receiveExport=async(worker,m)=>{if(worker!==active)return;exportBusy=false;exportButtons();if(m.kind==='error'){fail(m.error);return;}if(m.kind!=='export')return;
    if(m.action==='copy'){try{await navigator.clipboard.writeText(m.content);status.textContent='Rapport CSV complet copié, avec les décisions actuelles.';}catch{q('[data-fallback]').value=m.content;q('[data-fallback]').hidden=false;q('[data-fallback-label]').hidden=false;q('[data-fallback]').focus();q('[data-fallback]').select();status.textContent='Copie bloquée : le rapport complet est sélectionnable ci-dessous.';}}
    else{const url=URL.createObjectURL(new Blob([m.content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='rapport-assistant-lettrage-local.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Rapport CSV complet créé localement. Original inchangé.';}
  };
  function load(f,delimiter,encoding){clearError();if(!f){fail('Choisissez un fichier CSV.');return;}if(f.size>MAX_BYTES){fail('Fichier supérieur à 10 Mo : import refusé. Rapport précédent conservé.');return;}stopPending();let candidate;try{candidate=makeWorker();}catch{fail('Le Worker local est indisponible : aucun fichier transmis.');return;}pending=candidate;const id=++seq;status.textContent='Import et recherche locale en cours ; vous pouvez annuler.';q('[data-cancel]').hidden=false;exportButtons();candidate.onerror=()=>{if(pending!==candidate)return;stopPending();fail('Le traitement local a échoué ; rapport précédent conservé.');};candidate.onmessage=({data:m})=>{if(pending!==candidate||m.id!==id)return;if(m.kind==='progress'){status.textContent=`${m.count} lignes lues ; recherche des paires en cours.`;return;}if(m.kind==='error'){stopPending();fail(m.error);status.textContent='Import refusé ; saisie et rapport précédent conservés.';return;}active?.terminate();active=candidate;pending=null;result=m.result;decisions={};pairPage=0;linePage=0;exportBusy=false;q('#lettrage-filter').value='all';q('[data-cancel]').hidden=true;candidate.onmessage=({data})=>receiveExport(candidate,data);candidate.onerror=()=>{exportBusy=false;exportButtons();fail('Export local interrompu. Réimportez pour recréer le Worker.');};render();status.textContent=`Rapport prêt : ${result.lines.length} lignes analysées localement.`;q('#lettrage-result-title').focus({preventScroll:true});};candidate.postMessage({id,kind:'load',file:f,delimiter,encoding});}
  q('form').addEventListener('submit',e=>{e.preventDefault();const s=q('#lettrage-separator').value;load(file.files[0],s==='tab'?'\t':s,q('#lettrage-encoding').value);});
  file.addEventListener('change',()=>{q('[data-file-name]').textContent=`Fichier choisi : ${file.files[0]?.name??'aucun'}. Le rapport n’est remplacé qu’après un import réussi.`;});
  q('[data-example]').addEventListener('click',()=>{if(result||pending||file.files.length){fail('Réinitialisez explicitement avant de charger l’exemple fictif.');return;}load(new File([EXAMPLE_CSV],'exemple-lettrage-fictif.csv'),';','utf-8');});
  q('[data-cancel]').addEventListener('click',()=>{stopPending();status.textContent='Traitement annulé. Rapport précédent et original conservés.';});
  q('#lettrage-filter').addEventListener('change',()=>{linePage=0;render();});
  for(const prefix of ['pair','line'])for(const direction of ['prev','next'])q(`[data-${prefix}-${direction}]`).addEventListener('click',()=>{const step=direction==='prev'?-1:1;if(prefix==='pair')pairPage+=step;else linePage+=step;render();q(`[data-${prefix==='pair'?'pairs':'lines'}]`).parentElement.focus({preventScroll:true});});
  for(const [selector,action] of [['[data-copy]','copy'],['[data-export]','download']])q(selector).addEventListener('click',()=>{if(!active||!result||exportBusy||pending)return;clearError();exportBusy=true;exportButtons();active.postMessage({id:++seq,kind:'export',action,decisions:{...decisions}});});
  function reset(){stopPending();active?.terminate();active=null;result=null;decisions={};seq++;exportBusy=false;pairPage=0;linePage=0;q('form').reset();q('[data-result]').hidden=true;for(const s of ['[data-pairs]','[data-lines]','[data-sums]'])q(s).replaceChildren();q('[data-fallback]').value='';q('[data-fallback]').hidden=true;q('[data-fallback-label]').hidden=true;q('[data-summary]').textContent='';q('[data-file-name]').textContent='Fichier choisi : aucun.';clearError();exportButtons();status.textContent='Réinitialisé : données et décisions retirées de cette page, Worker terminé.';}
  q('[data-reset]').addEventListener('click',reset);window.addEventListener('pagehide',reset);
}
