import {test,expect} from '@playwright/test';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {demoSession,exportJson,exportCsv,createSession,addItem} from '../../src/lib/checklist-pieces.mjs';
const route='/outils-comptables-gratuits/checklist-pieces-comptables';
test.use({reducedMotion:'reduce'});
const download=async(page,format)=>{const wait=page.waitForEvent('download');await page.locator(`[data-cl-export="${format}"]`).click();return readFileSync(await(await wait).path(),'utf8');};
const upload=async(page,content,format='json')=>{await page.locator('details').filter({has:page.locator('#cl-file')}).evaluate(e=>e.open=true);await page.locator('#cl-format').selectOption(format);await page.locator('#cl-file').setInputFiles({name:`reprise.${format}`,mimeType:format==='json'?'application/json':'text/csv',buffer:Buffer.from(content)});await page.getByRole('button',{name:'Vérifier la reprise',exact:true}).click();};
for(const width of [320,375,768,1024,1440,1920])test(`checklist complète, réseau/stockages et reflow ${width}`,async({page,context})=>{
 await page.setViewportSize({width,height:900});await page.goto(route,{waitUntil:'networkidle'});const errors=[];page.on('pageerror',e=>errors.push(e.message));const requests=[];context.on('request',r=>requests.push(r.url()));
 const storage=()=>page.evaluate(async()=>({local:localStorage.length,session:sessionStorage.length,cookies:document.cookie,db:await indexedDB.databases(),caches:await caches.keys()}));const before=await storage();
 await page.getByRole('button',{name:'Charger l’exemple fictif',exact:true}).click();await expect(page.locator('[data-cl-item]')).toHaveCount(4);await expect(page.locator('#cl-message')).toHaveValue(/Relevé bancaire de septembre/);expect(await page.locator('#cl-message').inputValue()).not.toMatch(/Factures d’achat|Justificatif d’acquisition|Récapitulatif de paie/);await expect(page.locator('[data-cl-unknown]')).toContainText('Récapitulatif de paie');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const json=await download(page,'json'),csv=await download(page,'csv'),html=await download(page,'html');expect(JSON.parse(json)).toEqual(demoSession());expect(csv).toContain('neutralized');expect(html).toContain('Aucune pièce jointe');
 await page.locator('#cl-period').fill('Octobre 2026');await upload(page,json);await expect(page.locator('[data-cl-apply]')).toBeEnabled();await expect(page.locator('#cl-period')).toHaveValue('Octobre 2026');page.once('dialog',d=>d.dismiss());await page.locator('[data-cl-apply]').click();await expect(page.locator('#cl-period')).toHaveValue('Octobre 2026');page.once('dialog',d=>d.accept());await page.locator('[data-cl-apply]').click();await expect(page.locator('#cl-period')).toHaveValue('Septembre 2026');
 await upload(page,JSON.stringify({...demoSession(),version:99}));await expect(page.locator('[data-cl-error]')).toContainText('Version inconnue');expect(JSON.parse(await download(page,'json'))).toEqual(demoSession());
 await upload(page,csv,'csv');await expect(page.locator('[data-cl-apply]')).toBeEnabled();page.once('dialog',d=>d.accept());await page.locator('[data-cl-apply]').click();expect(JSON.parse(await download(page,'json'))).toEqual(demoSession());
 await page.locator('#cl-p2-label').fill('<img src=x onerror=alert(1)>');await expect(page.locator('.cl img')).toHaveCount(0);expect(await download(page,'html')).toContain('&lt;img');await page.locator('#cl-p2-label').fill('=1+1');expect(await download(page,'csv')).toContain("'=1+1");
 await page.locator('#cl-label').fill('Pièce libre');await page.locator('#cl-state').selectOption('missing');await page.getByRole('button',{name:'Ajouter la pièce',exact:true}).click();await expect(page.locator('#cl-message')).toHaveValue(/Pièce libre/);await page.getByRole('button',{name:'Supprimer p5',exact:true}).click();expect(await page.locator('#cl-message').inputValue()).not.toContain('Pièce libre');
 for(const id of ['p1','p2','p3','p4'])await page.locator(`#cl-${id}-state`).selectOption('received');await expect(page.locator('[data-cl-summary]')).toContainText('Terminé');await expect(page.locator('#cl-message')).toHaveValue('');await expect(page.locator('[data-cl-copy]')).toBeDisabled();
 await page.locator('#cl-p1-label').fill('');await expect(page.locator('[data-cl-error]')).toBeVisible();await expect(page.locator('[data-cl-export="json"]')).toBeDisabled();await expect(page.locator('#cl-p1-label')).toHaveAttribute('aria-describedby','cl-error');await page.locator('#cl-p1-label').fill('Factures d’achat');await page.locator('#cl-p1-label').focus();expect(await page.locator('#cl-p1-label').evaluate(e=>getComputedStyle(e).outlineStyle)).not.toBe('none');
 const graph=await page.locator('script[type="application/ld+json"]').evaluateAll(els=>els.flatMap(el=>{const g=JSON.parse(el.textContent);return g['@graph']??[g];}));for(const type of ['WebPage','WebApplication','BreadcrumbList'])expect(graph.some(n=>n['@type']===type)).toBe(true);await expect(page.locator('h1')).toHaveCount(1);const h1=await page.locator('h1').innerText();expect(graph.find(n=>n['@type']==='WebPage').headline).toBe(h1);await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content',h1);await expect(page.locator('link[rel=canonical]')).toHaveAttribute('href','https://memlia.fr'+route);
 expect(await storage()).toEqual(before);expect(requests).toEqual([]);expect(errors).toEqual([]);expect(await page.locator('script[src*="cloudflareinsights"]').count()).toBe(0);
 if(process.env.CHECKLIST_CAPTURE==='1'){const out='docs/strategy/site-v3/outils-ec-vague-4/checklist';mkdirSync(out,{recursive:true});if([375,1440].includes(width)){page.once('dialog',d=>d.accept());await page.locator('[data-cl-demo]').click();await page.evaluate(async()=>{for(let y=0;y<document.documentElement.scrollHeight;y+=600){window.scrollTo(0,y);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));}window.scrollTo(0,0);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});await page.screenshot({path:`${out}/checklist-${width}.png`,fullPage:true});}writeFileSync(`${out}/audit-${width}.json`,JSON.stringify({width,overflow:false,requests,errors,storage:await storage(),reflow:width===320?'équivalent 1280px à 400%':null},null,2));}
});
test('100 lignes, 101 refusées, annulation sans résultat appliqué',async({page})=>{
 await page.goto(route,{waitUntil:'networkidle'});await page.locator('[data-cl-demo]').click();let s=createSession();for(let i=0;i<100;i++)s=addItem(s,{family:'libre',label:'Pièce '+i,state:'unknown',note:''});await upload(page,exportJson(s));await expect(page.locator('[data-cl-apply]')).toBeEnabled();page.once('dialog',d=>d.accept());await page.locator('[data-cl-apply]').click();await expect(page.locator('[data-cl-item]')).toHaveCount(100);
 await page.locator('#cl-label').fill('101');await page.getByRole('button',{name:'Ajouter la pièce',exact:true}).click();await expect(page.locator('[data-cl-error]')).toContainText('100');await expect(page.locator('#cl-label')).toHaveValue('101');await expect(page.locator('[data-cl-item]')).toHaveCount(100);
 // A delayed reply reproduces cancellation independent of machine speed.
 await page.addInitScript(()=>{});await page.locator('#cl-file').setInputFiles({name:'large.json',mimeType:'application/json',buffer:Buffer.from(exportJson(s))});await page.evaluate(()=>{document.querySelector('[data-cl-import]').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));document.querySelector('[data-cl-cancel]').click();});await expect(page.locator('[data-cl-status]')).toContainText('annulée');await expect(page.locator('[data-cl-apply]')).toBeDisabled();await expect(page.locator('[data-cl-item]')).toHaveCount(100);
});
test('trame choisie et reset protégé, copie complète sans envoi',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto(route,{waitUntil:'networkidle'});await page.getByLabel('Achats',{exact:true}).check();await page.getByLabel('Banque',{exact:true}).check();await page.getByRole('button',{name:'Ajouter les familles choisies',exact:true}).click();await expect(page.locator('[data-cl-item]')).toHaveCount(2);await expect(page.locator('[data-cl-unknown] li')).toHaveCount(2);await expect(page.locator('#cl-message')).toHaveValue('');
 await page.locator('#cl-p2-state').selectOption('missing');await page.locator('[data-cl-copy]').click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(await page.locator('#cl-message').inputValue());page.once('dialog',d=>d.dismiss());await page.locator('[data-cl-reset]').click();await expect(page.locator('[data-cl-item]')).toHaveCount(2);page.once('dialog',d=>d.accept());await page.locator('[data-cl-reset]').click();await expect(page.locator('[data-cl-item]')).toHaveCount(0);await expect(page.locator('[data-cl-summary]')).toContainText('Liste vide');
});
