import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const route='/outils-comptables-gratuits/suivi-circularisation';
const csv='id;category;recipient;contact;referenceDate;currency;requestedAmount;confirmationType\n0007;client;<img src=x onerror=alert(1)>;"=HYPERLINK(""x"")";2026-01-01;EUR;100;open';
const headers=['id','category','recipient','contact','referenceDate','currency','requestedAmount','confirmationType'];
async function prepare(page,text=csv){await page.getByText('Importer un CSV : mapping, aperçu et sélection',{exact:true}).click();await page.locator('#circ-csv').setInputFiles({name:'fictif.csv',mimeType:'text/csv',buffer:Buffer.from(text)});await page.getByRole('button',{name:'Lire le CSV',exact:true}).click();await expect(page.locator('[data-circ-mapping] select')).toHaveCount(10);for(const h of headers)await page.locator(`[data-circ-mapping] select[name="${h}"]`).selectOption(h);await page.getByRole('button',{name:'Voir l’aperçu mappé',exact:true}).click();await expect(page.locator('[data-circ-import-summary]')).toContainText('1 lignes au total');}
test('Worker navigateur, mapping, validation humaine, texte inerte et lettre ouverte',async({page})=>{
 await page.goto(route);await page.evaluate(()=>document.fonts.ready);const requests=[];page.on('request',r=>requests.push(r));
 await prepare(page);await expect(page.locator('[data-circ-preview-rows]')).toContainText('<img src=x onerror=alert(1)>');await expect(page.locator('[data-circ-preview-rows] img')).toHaveCount(0);
 await page.getByRole('button',{name:'Ajouter la sélection validée',exact:true}).click();await expect(page.locator('[data-circ-error]')).toContainText('Validez explicitement');
 await page.locator('[data-circ-preview-rows] input').check();await page.locator('#circ-import-valid').check();await page.getByRole('button',{name:'Ajouter la sélection validée',exact:true}).click();await expect(page.locator('[data-circ-summary]')).toContainText('1 tiers');
 await page.getByRole('button',{name:'Ouvrir 0007',exact:true}).click();await page.locator('#circ-return').fill('Retour fictif au cabinet');await page.locator('#circ-letter-valid').check();await page.getByRole('button',{name:'Préparer une version de lettre',exact:true}).click();await expect(page.locator('[data-circ-letter-text]')).not.toContainText('100');await expect(page.locator('[data-circ-detail-summary]')).toContainText('Préparée');await expect(page.locator('[data-circ-reminder]')).toContainText('Envoi non renseigné');
 const dl=page.waitForEvent('download');await page.locator('[data-circ-export="csv"]').click();const output=await readFile(await(await dl).path(),'utf8');expect(output.charCodeAt(0)).toBe(0xFEFF);expect(output).toContain("'=HYPERLINK");
 const json=page.waitForEvent('download');await page.locator('[data-circ-export="json"]').click();expect(JSON.parse(await readFile(await(await json).path(),'utf8')).tiers[0].id).toBe('0007');
 expect(requests.filter(r=>r.method()!=='GET'||r.postData())).toEqual([]);expect(requests.every(r=>r.url().startsWith(new URL(page.url()).origin))).toBe(true);expect(requests.filter(r=>!r.url().includes('/_astro/'))).toEqual([]);
});
test('refus fichier volumineux, reprise invalide conserve les données et annulation',async({page})=>{
 await page.goto(route);await page.getByRole('button',{name:'Charger l’exemple fictif',exact:true}).click();await page.getByText('Reprendre une sauvegarde JSON',{exact:true}).click();await page.locator('#circ-json').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{}')});await page.getByRole('button',{name:'Reprendre le JSON',exact:true}).click();await expect(page.locator('[data-circ-error]')).toContainText('Structure');await expect(page.locator('[data-circ-summary]')).toContainText('3 tiers');
 await page.getByText('Importer un CSV : mapping, aperçu et sélection',{exact:true}).click();await page.locator('#circ-csv').setInputFiles({name:'large.csv',mimeType:'text/csv',buffer:Buffer.alloc(20_000_001)});await page.getByRole('button',{name:'Lire le CSV',exact:true}).click();await expect(page.locator('[data-circ-error]')).toContainText('avant lecture');
 await page.locator('#circ-csv').setInputFiles({name:'cancel.csv',mimeType:'text/csv',buffer:Buffer.from('a;b\n'+'x;y\n'.repeat(100000))});await page.evaluate(()=>{document.querySelector('[data-circ-import]').requestSubmit();document.querySelector('[data-circ-cancel]').click();});await expect(page.locator('[data-circ-status]')).toContainText('annulé');await expect(page.locator('[data-circ-summary]')).toContainText('3 tiers');await expect(page.locator('[data-circ-mapping] select')).toHaveCount(0);
});
test('chronologie erronée et devise différente restent explicites',async({page})=>{
 await page.goto(route);await page.getByRole('button',{name:'Charger l’exemple fictif',exact:true}).click();await page.getByRole('button',{name:'Ouvrir 001',exact:true}).click();await page.getByText('Ajouter une réponse ou un refus (historique conservé)',{exact:true}).click();await page.locator('#circ-response-date').fill('2026-01-09');await page.getByRole('button',{name:'Ajouter le retour',exact:true}).click();await expect(page.locator('[data-circ-error]')).toContainText('avant envoi');
 await page.locator('#circ-response-date').fill('2026-01-13');await page.locator('#circ-response-amount').fill('120');await page.locator('#circ-response-currency').fill('USD');await page.locator('[name="comparable"]').check();await page.getByRole('button',{name:'Ajouter le retour',exact:true}).click();await expect(page.locator('[data-circ-table]')).toContainText('Devise différente');await expect(page.locator('[data-circ-reconcile]')).toBeDisabled();await expect(page.locator('[data-circ-history]')).toContainText('Retour 2');
});
