import { test, expect } from '@playwright/test';
test('copie complète, exemple ne remplace pas sans accord, reflow 400 %',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await example(page);
 await page.getByRole('button',{name:'Copier le rapport complet'}).click();await expect(page.locator('[data-status]')).toContainText('copié');
 expect(await page.evaluate(()=>navigator.clipboard.readText())).toContain('comparateur-balances-1');
 const original=await page.locator('#csv-current').inputValue();page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Charger les deux CSV fictifs'}).click();await expect(page.locator('#csv-current')).toHaveValue(original);
 await page.setViewportSize({width:320,height:900});await expect(page.getByRole('button',{name:'Exporter le rapport CSV complet'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
test('annulation réelle du Worker sans résultat tardif, puis reprise',async({page})=>{
 await page.addInitScript(()=>{const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{postMessage(data:any){setTimeout(()=>super.postMessage(data),100)}} as typeof Worker;});
 await page.goto(route);await page.getByRole('button',{name:'Charger les deux CSV fictifs'}).click();await page.locator('#same-currency').check();await page.locator('#comparable').check();
 await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await page.getByRole('button',{name:'Annuler le traitement'}).click();await expect(page.locator('[data-status]')).toContainText('annulé');await expect(page.locator('[data-result]')).toBeHidden();await expect(page.locator('#csv-current')).not.toHaveValue('');
 await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await expect(page.locator('[data-result]')).toBeVisible();
});
test('fichier supérieur à 10 Mo refusé avant lecture',async({page})=>{
 await page.goto(route);await page.locator('#file-current').setInputFiles({name:'trop-grand.csv',mimeType:'text/csv',buffer:Buffer.alloc(10_000_001,65)});await page.getByRole('button',{name:'Lire N',exact:true}).click();await expect(page.locator('[data-error]')).toContainText('10 Mo');await expect(page.locator('#file-current')).not.toHaveValue('');await expect(page.locator('#csv-current')).toHaveValue('');
});
const route='/outils-comptables-gratuits/comparateur-balances-comptables';
async function example(page:any){await page.goto(route);await page.getByRole('button',{name:'Charger les deux CSV fictifs'}).click();await expect(page.locator('[data-status]')).toContainText('Exemple chargé');await page.locator('#same-currency').check();await page.locator('#comparable').check();await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await expect(page.locator('[data-result]')).toBeVisible();}
test('exemple, calcul exact, export et stockage/réseau inchangés',async({page})=>{await page.goto(route);const before=await page.evaluate(()=>({local:{...localStorage},session:{...sessionStorage},cookie:document.cookie}));const sent:string[]=[];page.on('request',r=>{if(['fetch','xhr','ping'].includes(r.resourceType()))sent.push(r.url())});await page.getByRole('button',{name:'Charger les deux CSV fictifs'}).click();await page.locator('#same-currency').check();await page.locator('#comparable').check();await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();const result=page.locator('[data-result]');await expect(result).toBeVisible();await expect(result).toContainText('30,00');await expect(result).toContainText('30.00 %');await expect(result).toContainText('20.00 %');await expect(result).toContainText('non calculable');await expect(result).toContainText('nouveau');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Exporter le rapport CSV complet'}).click();const d=await dl;const stream=await d.createReadStream();let csv='';for await(const chunk of stream!)csv+=chunk.toString();expect(csv).toContain('00123');expect(csv).toContain('non calculable');expect(csv).toContain('comparateur-balances-1');expect(csv).toContain('convention');expect(sent).toEqual([]);expect(await page.evaluate(()=>({local:{...localStorage},session:{...sessionStorage},cookie:document.cookie}))).toEqual(before);});
test('confirmations, refus ambigu et saisies conservées',async({page})=>{await page.goto(route);await page.getByRole('button',{name:'Charger les deux CSV fictifs'}).click();await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await expect(page.locator('[data-error]')).toContainText('confirmation');await page.locator('#same-currency').check();await page.locator('#comparable').check();const text='Compte;Libellé;Solde\n00123;Test;1,234';await page.locator('#csv-current').fill(text);await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await expect(page.locator('[data-error]')).toContainText('ambigu');await expect(page.locator('#csv-current')).toHaveValue(text);await expect(page.locator('[data-result]')).toBeHidden();});
test('300 comptes exportés sans troncature, pagination et périodes',async({page})=>{await example(page);const csv='Compte;Libellé;Solde\n'+Array.from({length:300},(_,i)=>`C${String(i).padStart(5,'0')};Fictif;130,00`).join('\n');await page.locator('#csv-current').fill(csv);await page.locator('#current-end').fill('2026-06-30');await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await expect(page.locator('[data-result]')).toContainText('302 comptes');await expect(page.locator('[data-warnings]')).toContainText('Durées différentes');await expect(page.locator('[data-table] tbody tr')).toHaveCount(50);await page.getByRole('button',{name:'Page suivante'}).click();await expect(page.locator('[data-page]')).toContainText('2 /');const dl=page.waitForEvent('download');await page.getByRole('button',{name:'Exporter le rapport CSV complet'}).click();const d=await dl;let csvOut='';for await(const chunk of (await d.createReadStream())!)csvOut+=chunk.toString();expect(csvOut.split('\n').filter(s=>s.startsWith('"compte";'))).toHaveLength(302);expect(csvOut).toContain('Durées différentes');});
test('doublons seulement sur confirmation, provenance et HTML inerte',async({page})=>{await example(page);await page.locator('#csv-current').fill('Compte;Libellé;Solde\n00123;=SUM(A1);100,00\n00123;"<img src=x onerror=alert(1)>";30,00');await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await expect(page.locator('[data-error]')).toContainText('doublon');await page.locator('#aggregate-current').check();await page.getByRole('button',{name:'Comparer les balances',exact:true}).click();await expect(page.locator('[data-result]')).toContainText('130,00');await expect(page.locator('[data-table]')).toContainText('2, 3');await expect(page.locator('[data-warnings]')).toContainText('divergents');expect(await page.locator('[data-table] img').count()).toBe(0);});
for(const width of [320,375,768,1024,1440,1920])test(`mobile/clavier ${width}`,async({page})=>{await page.setViewportSize({width,height:900});await example(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.locator('[data-table-region]').focus();await expect(page.locator('[data-table-region]')).toBeFocused();await page.keyboard.press('ArrowRight');await page.screenshot({path:`.qa/balances-${width}.png`,fullPage:true});});
test('import réel avec mapping, annulation et reset',async({page})=>{await page.goto(route);await page.locator('#file-previous').setInputFiles({name:'a.csv',mimeType:'text/csv',buffer:Buffer.from('Titre;Numéro;Crédit;Débit\nFictif;00123;0,00;100,00')});await page.getByRole('button',{name:'Lire N−1'}).click();await expect(page.locator('[data-status]')).toContainText('a.csv');await page.locator('#mode-previous').selectOption('debit-credit');await page.locator('#map-previous-account').selectOption('1');await page.locator('#map-previous-label').selectOption('0');await page.locator('#map-previous-debit').selectOption('3');await page.locator('#map-previous-credit').selectOption('2');await page.getByRole('button',{name:'Tout effacer'}).click();await expect(page.locator('#csv-previous')).toHaveValue('');await expect(page.locator('#file-previous')).toHaveValue('');await expect(page.locator('[data-result]')).toBeHidden();});
