import {test,expect,type Page} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const route='/outils-comptables-gratuits/fusionner-fichiers-csv';
const file=(name:string,text:string)=>({name,mimeType:'text/csv',buffer:Buffer.from(text)});
async function load(page:Page,files=[file('a.csv','ID;Montant\n00123;10\n002;20'),file('b.csv','Montant;ID\n30;003\n40;004\n50;005')]){await page.locator('#fusion-files').setInputFiles(files);await page.getByRole('button',{name:'Importer les fichiers',exact:true}).click();await expect(page.locator('[data-mapping]')).toBeVisible();}
async function merge(page:Page){await page.locator('[data-confirmed]').check();await page.locator('[data-merge]').click();await expect(page.locator('[data-result]')).toBeVisible();}
async function download(page:Page,format:string){const event=page.waitForEvent('download');await page.locator(`[data-export="${format}"]`).click();return readFile((await(await event).path())!,'utf8');}
test('mapping inversé, provenance, cinq lignes, exports complets et copie',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto(route);await load(page);await page.locator('[data-provenance]').check();await merge(page);
 await expect(page.locator('[data-table]')).toContainText('00123');await expect(page.locator('[data-summary]')).toContainText('5 lignes consolidées');await page.locator('[data-reviewed]').check();
 const csv=await download(page,'csv');expect(csv).toContain('"003";"30";"b.csv";"2"');const report=JSON.parse(await download(page,'report'));expect(report.files.map((f:any)=>f.inputRows)).toEqual([2,3]);expect(report.origins.length).toBe(5);
 await page.locator('[data-copy]').click();await expect(page.locator('[data-status]')).toContainText('copié');expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(csv);
 await page.locator('#fusion-map-0-0').fill('Code');await expect(page.locator('[data-result]')).toBeHidden();await expect(page.locator('[data-confirmed]')).not.toBeChecked();
 await page.locator('[data-confirmed]').check();await page.locator('[data-merge]').click();await expect(page.locator('[data-error]')).toContainText('union');await page.locator('[data-union]').check();await merge(page);await expect(page.locator('[data-summary]')).toContainText('cellules absentes');
 await page.locator('[data-reset]').click();await expect(page.locator('[data-mapping]')).toBeHidden();await expect(page.locator('[data-table]')).toBeEmpty();expect(await page.locator('#fusion-files').inputValue()).toBe('');
});
test('homonymes arrêtés, correction et ordre des fichiers',async({page})=>{
 await page.goto(route);await load(page,[file('a.csv','A;A\n1;2'),file('b.csv','A;B\n3;4')]);await page.locator('[data-confirmed]').check();await page.locator('[data-merge]').click();await expect(page.locator('[data-error]')).toContainText('Mapping ambigu');await expect(page.locator('[data-result]')).toBeHidden();
 await page.locator('#fusion-map-0-1').fill('B');await page.locator('[data-file="1"] button').click();await merge(page);await expect(page.locator('[data-table] tbody tr').first()).toContainText('3');
});
test('doublons conservés puis retirés, formule neutralisée et original intact',async({page})=>{
 await page.goto(route);const text='A;B\n00123;"=HYPERLINK(""x"")"';await load(page,[file('a.csv',text),file('b.csv',text)]);await page.locator('[data-provenance]').check();await merge(page);await expect(page.locator('[data-summary]')).toContainText('2 lignes consolidées');
 await page.locator('[data-dedup]').check();await merge(page);await expect(page.locator('[data-summary]')).toContainText('1 lignes consolidées');await page.locator('[data-reviewed]').check();expect(await download(page,'csv')).toContain("'=HYPERLINK");const report=JSON.parse(await download(page,'report'));expect(report.removedRows).toBe(1);expect(report.neutralizations.length).toBe(1);await expect(page.locator('[data-table]')).toContainText('=HYPERLINK("x")');
});
test('Windows-1252 par fichier, multiline et refus de structure',async({page})=>{
 await page.goto(route);await page.locator('#fusion-files').setInputFiles([{name:'cp.csv',mimeType:'text/csv',buffer:Buffer.from('ID;Nom\r\n00123;"Andr\xe9\r\nsuite"\r\n004;Z','latin1')},file('b.csv','ID|Nom\n005|Y')]);await page.locator('#fusion-encoding-0').selectOption('windows-1252');await page.locator('#fusion-delimiter-1').selectOption('|');await page.getByRole('button',{name:'Importer les fichiers',exact:true}).click();await expect(page.locator('[data-mapping]')).toBeVisible();await page.locator('[data-provenance]').check();await merge(page);await expect(page.locator('[data-table]')).toContainText('André');await expect(page.locator('[data-table] tbody tr').nth(1)).toContainText('4');
 await page.locator('[data-example]').click();await expect(page.locator('[data-error]')).toContainText('Réinitialisez');await page.locator('[data-reset]').click();await page.locator('#fusion-files').setInputFiles([file('a.csv','A;B\n1'),file('b.csv','A;B\n2;3')]);await page.getByRole('button',{name:'Importer les fichiers',exact:true}).click();await expect(page.locator('[data-error]')).toContainText('colonnes');await expect(page.locator('[data-result]')).toBeHidden();
});
test('annulation immédiate et refus supérieur à 20 Mo sans succès',async({page})=>{
 await page.goto(route);await page.evaluate(()=>{document.querySelector<HTMLButtonElement>('[data-example]')!.click();document.querySelector<HTMLButtonElement>('[data-cancel]')!.click();});await expect(page.locator('[data-status]')).toContainText('annulé');await expect(page.locator('[data-mapping]')).toBeHidden();
 await page.locator('[data-reset]').click();await page.locator('#fusion-files').setInputFiles([file('a.csv','A;B\n1;2'),file('b.csv','A;B\n3;4')]);await page.evaluate(()=>{const c=document.querySelector('[data-config]')!;const input=document.querySelector<HTMLInputElement>('#fusion-files')!;const dt=new DataTransfer();dt.items.add(new File([new Uint8Array(20*1024*1024)],'big.csv'));dt.items.add(new File(['A;B\n1;2'],'b.csv'));input.files=dt.files;input.dispatchEvent(new Event('change'));});await page.getByRole('button',{name:'Importer les fichiers',exact:true}).click();await expect(page.locator('[data-error]')).toContainText('20 Mo');await expect(page.locator('[data-result]')).toBeHidden();
});
test('pagination export complet, zéro transfert contenu et stockage',async({page})=>{
 await page.goto(route);await page.waitForLoadState('networkidle');const requests:string[]=[];page.on('request',r=>{expect(r.method()).toBe('GET');expect(r.postData()).toBeNull();if(!r.url().includes('/_astro/'))requests.push(r.url());});
 await page.evaluate(()=>{(window as any).writes=[];Storage.prototype.setItem=(...args:any[])=>{(window as any).writes.push(args);throw Error('storage');};IDBFactory.prototype.open=(...args:any[]):any=>{(window as any).writes.push(args);throw Error('idb');};});
 await load(page,[file('a.csv','ID;V\n'+Array.from({length:30},(_,i)=>`${i};x`).join('\n')),file('b.csv','V;ID\nx;30')]);await merge(page);await expect(page.locator('[data-table] tbody tr')).toHaveCount(25);await page.locator('[data-next]').click();await expect(page.locator('[data-table] tbody tr')).toHaveCount(6);await page.locator('[data-reviewed]').check();const report=JSON.parse(await download(page,'report'));expect(report.outputRows).toBe(31);expect((await download(page,'csv')).split('\r\n').length).toBe(33);expect(requests).toEqual([]);expect(await page.evaluate(()=>(window as any).writes)).toEqual([]);expect(await page.evaluate(()=>[localStorage.length,sessionStorage.length,document.cookie])).toEqual([0,0,'']);
});
for(const width of [320,375,768,1024,1440,1920])test(`mobile, clavier, SEO et export ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await page.emulateMedia({reducedMotion:'reduce'});await page.goto(route);await expect(page.locator('h1')).toHaveCount(1);const h1=await page.locator('h1').innerText();await expect(page.locator('meta[property="og:title"]')).toHaveAttribute('content',h1);await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href','https://memlia.fr'+route);
 await page.locator('[data-example]').click();await expect(page.locator('[data-mapping]')).toBeVisible();await page.locator('[data-provenance]').check();await page.locator('[data-confirmed]').focus();await page.keyboard.press('Space');await page.locator('[data-merge]').click();await expect(page.locator('[data-result]')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('[data-reviewed]').focus();await page.keyboard.press('Space');await download(page,'csv');await page.locator('.table-scroll').focus();await page.keyboard.press('ArrowRight');await page.locator('.table-scroll').evaluate(e=>{e.scrollLeft=e.scrollWidth;});if(width<=375)expect(await page.locator('.table-scroll').evaluate(e=>e.scrollLeft>0)).toBe(true);await page.locator('.table-scroll').evaluate(e=>{e.scrollLeft=0;});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`docs/qa/fusion-csv/fusion-${width}.png`,fullPage:true});
});
