import assert from 'node:assert/strict';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, extname } from 'node:path';
import { createServer } from 'node:http';
import { chromium } from '@playwright/test';
import { auditerContratBlog } from '../../../scripts/verify-blog-contract.mjs';
const slug='verifier-reponse-ia-comptabilite',dir='editorial/recettes/'+slug,dist=resolve('.qa/render-'+slug);
const contract=auditerContratBlog({root:process.cwd(),dist,slugs:[slug]});assert.equal(contract.pass,true,JSON.stringify(contract));
const server=createServer((req,res)=>{let p=resolve(dist,'.'+new URL(req.url,'http://localhost').pathname);if(!p.startsWith(dist+'/'))return res.writeHead(403).end();if(!existsSync(p)&&!extname(p))p+='.html';if(!existsSync(p))return res.writeHead(404).end();const types={'.html':'text/html','.css':'text/css','.js':'text/javascript','.webp':'image/webp','.avif':'image/avif','.woff2':'font/woff2'};res.setHeader('Content-Type',types[extname(p)]||'application/octet-stream');res.end(readFileSync(p));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch();const results=[];
try{for(const width of [1280,390]){const page=await browser.newPage({viewport:{width,height:900}});const errors=[],failures=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push({url:r.url(),status:r.status()});});await page.goto('http://127.0.0.1:'+server.address().port+'/blog/'+slug);await page.evaluate(()=>document.fonts.ready);await page.locator('[data-blog-proof]').last().scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('[data-blog-proof] img')].every(i=>i.complete&&i.naturalWidth>0));
const state=await page.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,h1:document.querySelectorAll('h1').length,canonical:document.querySelector('link[rel=canonical]')?.href,title:document.title,description:document.querySelector('meta[name=description]')?.content,images:[...document.querySelectorAll('[data-blog-proof] img')].map(i=>({src:i.getAttribute('src'),naturalWidth:i.naturalWidth,alt:i.alt})),links:[...document.querySelectorAll('.article-corps a[href^="/"]')].map(a=>a.getAttribute('href')),schema:[...document.querySelectorAll('script[type="application/ld+json"]')].map(s=>JSON.parse(s.textContent)),text:document.querySelector('.article-corps').innerText,tables:[...document.querySelectorAll('.article-corps table')].map(t=>({rows:t.rows.length,cols:t.rows[0].cells.length,scrollParent:t.parentElement.scrollWidth>t.parentElement.clientWidth}))}));
assert.equal(state.overflow,false);assert.equal(state.h1,1);assert.equal(state.canonical,'https://memlia.fr/blog/'+slug);assert.equal(state.images.length,2);assert.equal(errors.length,0);assert.equal(failures.length,0);assert.ok(state.text.includes('SOURCE_INTROUVABLE'));assert.ok(state.text.includes('Aucun modèle'));for(const href of state.links){const file=href.split('#')[0];assert.ok(existsSync(resolve(dist,'.'+file+'.html'))||existsSync(resolve(dist,'.'+file+'/index.html')),href);}
for(let i=0;i<2;i++)await page.locator('[data-blog-proof]').nth(i).screenshot({path:dir+'/rendu-figure-'+width+'-'+i+'.png'});await page.screenshot({path:dir+'/rendu-'+width+'.png',fullPage:true});results.push({...state,text:undefined,errors,failures});await page.close();}}
finally{await browser.close();server.close();}
writeFileSync(dir+'/verification-locale.json',JSON.stringify({checkedAt:new Date().toISOString(),contract,browser:results},null,2)+'\n');console.log(JSON.stringify({contract,browser:results.map(({schema,...r})=>({...r,schemaTypes:schema.flatMap(s=>s['@graph']||[s]).map(s=>s['@type'])}))},null,2));
