"""Generate the canonical page matrix and testable graph, docs only."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
rows=[]
def page(url,name,persona,jtbd,intent,primary,secondary,funnel,mission,proof,cta,schema,parent,priority,quality,outgoing,nav='contextuel'):
 rows.append(dict(url=url,name=name,persona=persona,jtbd=jtbd,intent=intent,primary_keyword=primary,secondary_keywords=secondary,volume='ND',difficulty='ND',funnel=funnel,mission=mission,proof=proof,cta=cta,schema=schema,parent=parent,priority=priority,quality=quality,outgoing=outgoing,nav=nav))
S='/automatisation-cabinet-comptable';M='/methode';G='/garanties';A='/a-propos';C='/contact';B='/blog';R='/ressources';L='/glossaire';P=B+'/controler-les-bulletins-de-paie-avant-la-dsn';T=B+'/suivre-la-production-sociale-dans-excel';N=B+'/comprendre-les-comptes-rendus-metier-dsn';LEGAL='/mentions-legales';PRIV='/politique-de-confidentialite'
page('/','Accueil','Dirigeant / expert-comptable','Savoir si Memlia répond au travail répétitif du cabinet','Commerciale catégorie — historique coffre','automatisation cabinet comptable',['IA cabinet expertise comptable'],'Découverte','Automatiser le répétitif, garder la décision','Illustrations fictives proofs.ts ; pas ROI client','Identifier une tâche à automatiser → /contact',['Organization','WebSite','Service','FAQPage'],'—','P0 — adapter','Service/cible compris au premier écran ; pas copie du détail service',[S,M,G,R,B,A,C,LEGAL,PRIV],'logo + footer')
page(S,'Automatisation sur mesure','Dirigeant + référent outils','Définir une tâche et savoir quel livrable acheter','Commerciale service — déduction business + coffre','service automatisation sur mesure cabinet comptable',['automatiser tâches répétitives cabinet','automatisation Excel cabinet'],'Évaluation','Votre tâche, vos règles, un résultat à vérifier','Règles/limites et illustrations fictives ; compatibilité à qualifier','Identifier une tâche à automatiser → /contact',['Service','WebPage','BreadcrumbList'],'/','P0 — créer','Livrables, exclusions, outils et critères de devis concrets ; aucune fonction non livrée',[M,G,P,T,C],'header Automatisation')
page(M,'Méthode','Dirigeant / responsable social','Comprendre la mission et sa recette','Information commerciale — objection business','méthode automatisation Memlia',['cadrage automatisation cabinet','recette automatisation'],'Évaluation','Observer, cadrer, éprouver, faire valider','proofs.ts 04–07, cas fictifs et refus attendus','Décrire votre tâche → /contact',['WebPage','BreadcrumbList'],'/','P0 — créer','Chaque étape nomme entrée, sortie, décision ; exemple de refus, maintenance bornée',[S,G,A,C],'header Méthode')
page(G,'Garanties et limites','Référent outils + dirigeant','Évaluer confidentialité, contrôle et conditions de confiance','Réassurance — objection business','garanties automatisation Memlia',['validation humaine IA cabinet','confidentialité automatisation cabinet'],'Décision','La proposition ne prend pas la décision','Principe fail-closed et vue agrégée fictive ; pas attestation RGPD','Parlons de vos contraintes → /contact',['WebPage','BreadcrumbList'],'/','P0 — créer','Distinguer engagement de méthode, dispositif vérifié et contrat ; aucun hébergement présumé',[M,PRIV,C],'header Garanties')
page(A,'À propos','Dirigeant / lecteur des guides','Identifier le responsable et son rôle réel','Navigationnelle marque — pas page à volume','Kevin Kitanga Memlia',['fondateur Memlia'],'Confiance','Une responsabilité identifiée, un périmètre assumé','Auteur public des deux articles ; identité légale actuelle, pas diplôme supposé','Parler de votre cabinet → /contact',['AboutPage','Person','BreadcrumbList'],'/','P0 — créer','Kevin Kitanga cohérent byline/RSS/schema ; lieu activité distinct du siège',[M,B,C,LEGAL],'footer Memlia + bylines')
page(C,'Contact','Acheteur / responsable social','Comprendre le prochain échange et choisir le canal','Transactionnelle marque','contact Memlia',['automatisation cabinet devis'],'Décision','Commençons par décrire une tâche, sans données client','Deux destinations Cal.com déjà dans site.mjs + email public','Réserver un échange → Cal.com existant ; Écrire à Memlia → mailto existant',['ContactPage','BreadcrumbList'],'/','P0 — créer','Aucun formulaire/upload ; expliquer fichiers exclus et prochain pas, liens utilisables sans JS',[S,M,G,PRIV],'header CTA')
page(B,'Blog','Responsable social / dirigeant','Apprendre à préparer et vérifier avant automatisation','Informationnelle hub éditorial','méthodes automatisation cabinet',['contrôle paie','suivi production sociale'],'Découverte','Des méthodes pour automatiser sans déléguer son jugement','Deux articles datés, sourcés et signés Kevin Kitanga','Identifier une tâche à automatiser → /contact',['CollectionPage','BreadcrumbList'],'/','P0 — adapter','Chapeau précis GLOBAL-MESSAGING ; pas hub de téléchargements ; pas taxonomie vide',[P,T,N,R,S,C],'header Blog')
page(P,'Contrôler les bulletins avant DSN','Responsable production sociale','Structurer la revue avant la transmission','Informationnelle métier — coffre et contenu existant','contrôle bulletin de paie avant DSN',['contrôle cohérence paie','checklist contrôle paie'],'Découverte / évaluation','L’outil prépare les écarts, le cabinet vérifie','Article existant et sources ; attestation métier non établie','Cadrer un contrôle répétitif → /contact',['BlogPosting','BreadcrumbList'],'/blog','P0 — préserver et mailler','URL et texte fact-checké préservés ; distinguer bulletin/DSN ; aucun label conformité',[B,T,M,S,C,A])
page(T,'Suivre la production sociale','Responsable social / dirigeant','Suivre étapes et exceptions du portefeuille','Méthode/objet — historique coffre','suivi de production sociale cabinet comptable',['suivi dossiers paie Excel','tableau de bord pôle social'],'Découverte / évaluation','Piloter les dossiers, pas surveiller les personnes','Article existant, modèle conceptuel agrégé ; aucun fichier à promettre','Cadrer votre suivi → /contact',['BlogPosting','BreadcrumbList'],'/blog','P0 — préserver et mailler','Aucun classement individuel ; URL conservée ; étapes plutôt qu’activité salariés',[B,P,S,G,C,A])
page(R,'Ressources','Lecteur cherchant un format utile','Trouver une aide par tâche puis format','Informationnelle orientation — chaîne existante','ressources automatisation cabinet',['guides cabinet','modèles cabinet'],'Découverte','Choisir une ressource pour comprendre, vérifier ou préparer','Candidat et preuve détenus par la chaîne Ressources ; live 404 au relevé','Choisir une ressource ; cadrer une tâche → /contact',['CollectionPage','BreadcrumbList'],'/','EXISTANT — autre chaîne','Ne publier aucun lien vers objet absent ; respecter identité et contrats du candidat Ressources',[B,L,S,C],'header Ressources')
page(L,'Glossaire','Lecteur des guides','Comprendre un terme sans quitter le parcours','Informationnelle définitions — chaîne existante','glossaire automatisation cabinet',['définitions paie DSN'],'Découverte','Des définitions pour mieux vérifier les propositions','Contenus et slugs enfants détenus par chaîne Ressources, non inventés ici','Lire la méthode correspondante',['CollectionPage','BreadcrumbList'],'/','EXISTANT — autre chaîne','Pas de doublon de termes ni de pages maigres nouvelles ; importer routes réelles après release',[R,B,P,T],'Ressources + footer')
page(LEGAL,'Mentions légales','Tout visiteur','Identifier l’éditeur','Légale, hors cible SEO','N/A légal',['N/A'],'Confiance','Responsabilité éditoriale explicite','Page légale courante ; aucune donnée juridique recalculée','Contacter Memlia → /contact',['WebPage'],'/','P0 — préserver','noindex/follow ; pas téléphone ni TVA non confirmée ; siège sourcé',[A,C,PRIV],'footer légal')
page(PRIV,'Confidentialité','Tout visiteur','Comprendre les traitements liés au site','Légale, hors cible SEO','N/A confidentialité',['N/A'],'Confiance','Ne collecter que ce qui est utile','Politique actuelle ; aligner sur absence de formulaire et outils réellement utilisés','Contacter Memlia → /contact',['WebPage'],'/','P0 — préserver','noindex/follow ; pas promesse hébergement/consentement non vérifiée',[G,C,LEGAL],'footer légal')
page(N,'Comprendre les comptes rendus métier DSN','Gestionnaire / responsable social','Interpréter un retour sans le confondre avec une validation globale','Informationnelle — recherche historique, à rafraîchir','compte rendu métier DSN',['lire retour DSN','anomalie CRM DSN'],'Découverte','Comprendre le retour avant de décider de la suite','Sources institutionnelles à reconsulter ; aucun brouillon ni preuve métier actuelle','Lire les contrôles avant DSN ; cadrer une tâche → /contact',['BlogPosting','BreadcrumbList'],'/blog','P2 — ensuite conditionnel','Avant création : zéro doublon Ressources, sources officielles fraîches, exemple fictif et limites',[B,P,M,C,A])
for r in rows:
 r['incoming']=[s['url'] for s in rows if r['url'] in s['outgoing']]
 r['indexability']='noindex, follow' if r['url'] in [LEGAL,PRIV] else 'index, follow uniquement une fois publiée et acceptée'
 r['title']=r['name']+' | Memlia'
 if r['url']=='/':r['title']='Automatisation IA pour cabinets comptables | Memlia'
 r['description']=r['mission']+'. '+r['jtbd']+'. Découvrez la méthode et les limites du service Memlia.'
ROOT.joinpath('page-inventory.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2)+'\n')
fields=['url','name','persona','jtbd','intent','primary_keyword','secondary_keywords','volume','difficulty','funnel','mission','proof','cta','schema','parent','incoming','outgoing','priority','quality','nav','indexability','title','description']
md='# Inventaire canonique des pages\n\n15/09/2026. Généré par build-inventory.py ; page-inventory.json est la matrice machine. Tous les volumes/KD sont ND. Les routes P2 et appartenant à Ressources ne sont pas des liens à rendre avant leur publication. Les titres/descriptions constituent le point de départ de la copy, à spécialiser sans promesse supplémentaire.\n\n'
md+='| URL | Page | Parent | Navigation | Priorité |\n|---|---|---|---|---|\n'
for r in rows:md+='| '+' | '.join(str(r[k]) for k in ['url','name','parent','nav','priority'])+' |\n'
for r in rows:
 md+='\n## '+r['url']+'\n\n'
 for k in fields[1:]:
  v=r[k];md+='- **'+k+'** : '+(('; '.join(v) or '— racine') if isinstance(v,list) else v)+'\n'
ROOT.joinpath('PAGE-INVENTORY.md').write_text(md)
print('Generated',len(rows),'unique page definitions')
