import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,existsSync,statSync} from 'node:fs';
import {resolve,extname} from 'node:path';
import {createServer} from 'node:http';
import {chromium} from '@playwright/test';
import sharp from 'sharp';
import {auditerContratBlog} from '../../../scripts/verify-blog-contract.mjs';
const slug='automatiser-avec-ia-sans-changer-logiciel',dir='editorial/recettes/'+slug,dist=resolve('.qa/render-'+slug);
const contract=auditerContratBlog({root:process.cwd(),dist,slugs:[slug]});assert.equal(contract.pass,true,JSON.stringify(contract));
const server=createServer((req,res)=>{let p=resolve(dist,'.'+new URL(req.url,'http://localhost').pathname);if(!p.startsWith(dist+'/'))return res.writeHead(403).end();if(!existsSync(p)&&!extname(p))p+='.html';if(!existsSync(p))return res.writeHead(404).end();res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.woff2':'font/woff2','.webp':'image/webp','.avif':'image/avif'})[extname(p)]||'application/octet-stream');res.end(readFileSync(p));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch(),results=[];
try{for(const width of [1280,390]){
 const page=await browser.newPage({viewport:{width,height:900}}),errors=[],failures=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)failures.push({url:r.url(),status:r.status()});});
 await page.goto('http://127.0.0.1:'+server.address().port+'/blog/'+slug);await page.evaluate(()=>document.fonts.ready);await page.locator('[data-blog-proof]').last().scrollIntoViewIfNeeded();await page.waitForFunction(()=>[...document.querySelectorAll('[data-blog-proof] img')].every(i=>i.complete&&i.naturalWidth));
 const state=await page.evaluate(()=>({width:innerWidth,overflow:document.documentElement.scrollWidth>innerWidth,lang:document.documentElement.lang,h1:[...document.querySelectorAll('h1')].map(h=>h.innerText),canonical:document.querySelector('link[rel=canonical]')?.href,robots:document.querySelector('meta[name=robots]')?.content,title:document.title,og:document.querySelector('meta[property="og:title"]')?.content,author:document.querySelector('meta[name=author]')?.content,schema:[...document.querySelectorAll('script[type="application/ld+json"]')].flatMap(s=>{const j=JSON.parse(s.textContent);return j['@graph']||[j];}),images:[...document.querySelectorAll('[data-blog-proof] img')].map(i=>({src:i.getAttribute('src'),alt:i.alt,w:i.naturalWidth,h:i.naturalHeight})),links:[...document.querySelectorAll('.article-corps a[href^="/"]')].map(a=>a.getAttribute('href')),tables:[...document.querySelectorAll('.article-corps table')].map(t=>({headers:[...t.querySelectorAll('th')].map(x=>x.innerText),rows:[...t.querySelectorAll('tbody tr')].map(r=>[...r.cells].map(c=>c.innerText))})),text:document.querySelector('.article-corps').innerText,toc:!!document.querySelector('.article-toc,nav[aria-label*="Sommaire"]')}));
 assert.equal(state.overflow,false);assert.equal(state.h1.length,1);assert.equal(state.lang,'fr');assert.equal(state.canonical,'https://memlia.fr/blog/'+slug);assert.equal(state.og,state.h1[0]);assert.equal(state.author,'Kevin Kitanga');assert.equal(state.images.length,2);for(const i of state.images){assert.equal(i.w,1600);assert.equal(i.h,900);assert.ok(i.alt&&!i.src.includes('-mobile'));}
 assert.ok(state.text.includes('Aucun modèle'));assert.ok(state.text.includes('VALIDATION_PERIMEE'));assert.ok(state.text.includes('séquentiel'));assert.ok(state.tables.every(t=>t.headers.length));assert.equal(state.tables[0].rows.length,15);assert.equal(state.tables[3].rows.length,8);
 for(const href of state.links){const [path,anchor]=href.split('#'),p=[resolve(dist,'.'+path+'.html'),resolve(dist,'.'+path+'/index.html')].find(existsSync);assert.ok(p,href);if(anchor)assert.ok(readFileSync(p,'utf8').includes('id="'+anchor+'"'),href);}
 const scroll=[];for(const table of await page.locator('.article-corps table').all()){const s=await table.evaluate(t=>{let p=t.parentElement;while(p!==document.body&&!(['auto','scroll'].includes(getComputedStyle(p).overflowX)&&p.scrollWidth>p.clientWidth))p=p.parentElement;if(p===document.body)return {needed:false};p.scrollLeft=p.scrollWidth;return {needed:true,left:p.scrollLeft,max:p.scrollWidth-p.clientWidth};});if(s.needed)assert.ok(s.left>0);scroll.push(s);}
 for(let i=0;i<2;i++)await page.locator('[data-blog-proof]').nth(i).screenshot({path:dir+'/rendu-figure-'+width+'-'+i+'.png'});await page.screenshot({path:dir+'/rendu-'+width+'.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);results.push({...state,text:undefined,scroll,errors,failures});await page.close();
}}finally{await browser.close();await new Promise(r=>server.close(r));}
const images=[];for(const id of ['passage-registre','passage-reprises']){const path='public/proofs/blog/'+id+'.webp',m=await sharp(path).metadata();assert.equal(m.width,1600);assert.equal(m.height,900);assert.ok(statSync(path).size<150000);images.push({path,...m,bytes:statSync(path).size});}
const output={checkedAt:new Date().toISOString(),contract,browser:results,images};writeFileSync(dir+'/verification-locale.json',JSON.stringify(output,null,2));console.log(JSON.stringify({...output,browser:results.map(({schema,...r})=>({...r,schemaTypes:schema.map(x=>x['@type'])}))},null,2));
